module.exports = {
  env: {
    NEXT_PUBLIC_SENDGRID_API_KEY: process.env.NEXT_PUBLIC_SENDGRID_API_KEY,
    NEXT_PUBLIC_TO_EMAIL_ADDRESS: process.env.NEXT_PUBLIC_TO_EMAIL_ADDRESS,
    NEXT_PUBLIC_SENDGRID_API_KEY: process.env.NEXT_PUBLIC_FROM_EMAIL_ADDRESS,
  },
}
